# Example config to read from two modbus sources and push
# to a victoriametrics instance
VMURL: "http://192.168.25.1:8428/api/v1/import/prometheus"
modbusTimeout: 1s
pushTimeout: 10s
updateDelay: 5s
cacheValidTime: 10s
longestFailTime: 2m
sources:
  - host: 192.168.25.147:502
    name: solis
    pause: 5ms
    lowWordFirst: false
    registers:
      - ID: 33130
        name: grid
        description: Power from grid (negative is sold)
        openMetricType: gauge
        modbusType: 1
        length: 2
        isSigned: true
        divisor: 1
        unit: W
      - ID: 34622
        name: "solar_production"
        description: "Current solar production"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 1
        unit: "W"
        isSigned: false
      - ID: 33139
        name: "soc"
        description: "Battery state of charge"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 1
        unit: "%"
        isSigned: false
      - ID: 33140
        name: "soh"
        description: "Battery state of health"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 1
        unit: "%"
        isSigned: false
      - ID: 33149
        name: "battery"
        description: "Power from battery"
        openMetricType: "gauge"
        modbusType: 1
        length: 2
        divisor: 1
        unit: "W"
        isSigned: true
      - ID: 33135
        name: "battery_charge_status"
        description: "Whatever battery is in standby, charging or discharging"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 1
        unit: ""
        isSigned: false
      - ID: 33147
        name: "load"
        description: "Current system load"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 1
        unit: "W"
        isSigned: false
  - host: 192.168.25.196:502
    name: nibe
    pause: 0.05s
    lowWordFirst: false
    registers:
      - ID: 1
        name: "current_outdoor_temperature"
        description: "Current outdoor temperature"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 2
        name: "supply_line_ep23bt2"
        description: "Supply line (EP23-BT2)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 3
        name: "supply_line_ep22bt2"
        description: "Supply line (EP22-BT2)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 4
        name: "supply_line_ep21bt2"
        description: "Supply line (EP21-BT2)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 5
        name: "supply_line_bt2"
        description: "Supply line (BT2)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 7
        name: "return_line_bt3"
        description: "Return line (BT3)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 8
        name: "hot_water_top"
        description: "Hot water top (BT7)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 9
        name: "hot_water_charging"
        description: "Hot water charging (BT6)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 10
        name: "brine_in"
        description: "Brine in (BT10)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 11
        name: "brine_out"
        description: "Brine out (BT11)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 12
        name: "condensor_supply_line"
        description: "Condensor supply line (BT12)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 13
        name: "discharge"
        description: "Discharge (BT14)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 14
        name: "liquid_line"
        description: "Liquid line (BT15)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 16
        name: "suction_gas"
        description: "Suction gas (BT17)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 21
        name: "collector_in"
        description: "Collector in (AZ10-BT26)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 22
        name: "collector_out"
        description: "Collector out (AZ10-BT27)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 31
        name: "return_line_eq1bt65"
        description: "Return line (EQ1-BT65)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 36
        name: "temperature_limiter_eb100fd1"
        description: "Temperature limiter (EB100-FD1)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 1
        unit: ""
        isSigned: true
      - ID: 37
        name: "average_temperature"
        description: "Average temperature (BT1)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 40
        name: "flow_sensor_bf1"
        description: "Flow sensor (BF1)"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "l/min"
        isSigned: true
      - ID: 2176
        name: "current_power_w"
        description: "Current power (2176)"
        openMetricType: "gauge"
        modbusType: 1
        length: 2
        divisor: 1
        unit: "W"
        isSigned: false
      - ID: 2305
        name: "energy_log_current_power_consumption"
        description: "Energy log current power consumption"
        openMetricType: "gauge"
        modbusType: 1
        length: 2
        divisor: 100
        unit: "kW"
        isSigned: false
      - ID: 2408
        name: "energy_log_current_power_consumption_components"
        description: "Energy log current power consumption components"
        openMetricType: "gauge"
        modbusType: 1
        length: 2
        divisor: 100
        unit: "kW"
        isSigned: false
      - ID: 2335
        name: "compressor_total_time_energy_storage_main_unit_ep14"
        description: "Compressor total time energy storage main unit (EP14)"
        openMetricType: "counter"
        modbusType: 1
        length: 2
        divisor: 1
        unit: "h"
        isSigned: false
      - ID: 2337
        name: "compressor_total_time_energy_storage_main_unit_ep15"
        description: "Compressor total time energy storage main unit (EP15)"
        openMetricType: "counter"
        modbusType: 1
        length: 2
        divisor: 1
        unit: "h"
        isSigned: false
      - ID: 2339
        name: "compressor_total_time_energy_storage_heat_pump_1_ep14"
        description: "Compressor total time energy storage heat pump 1 (EP14)"
        openMetricType: "counter"
        modbusType: 1
        length: 2
        divisor: 1
        unit: "h"
        isSigned: false
      - ID: 2341
        name: "compressor_total_time_energy_storage_heat_pump_1_ep15"
        description: "Compressor total time energy storage heat pump 1 (EP15)"
        openMetricType: "counter"
        modbusType: 1
        length: 2
        divisor: 1
        unit: "h"
        isSigned: false
      - ID: 2343
        name: "compressor_total_time_energy_storage_heat_pump_2_ep14"
        description: "Compressor total time energy storage heat pump 2 (EP14)"
        openMetricType: "counter"
        modbusType: 1
        length: 2
        divisor: 1
        unit: "h"
        isSigned: false
      - ID: 2345
        name: "compressor_total_time_energy_storage_heat_pump_2_ep15"
        description: "Compressor total time energy storage heat pump 2 (EP15)"
        openMetricType: "counter"
        modbusType: 1
        length: 2
        divisor: 1
        unit: "h"
        isSigned: false
      - ID: 2727
        name: "current_power"
        description: "Current power (2727)"
        openMetricType: "gauge"
        modbusType: 1
        length: 2
        divisor: 100
        unit: "kW"
        isSigned: false
      - ID: 1577
        name: "heating_including_added_heat"
        description: "Heating including added heat"
        openMetricType: "counter"
        modbusType: 1
        length: 2
        divisor: 10
        unit: "kWh"
        isSigned: false
      - ID: 1575
        name: "hot_water_including_added_heat"
        description: "Hot water including added heat"
        openMetricType: "counter"
        modbusType: 1
        length: 2
        divisor: 10
        unit: "kWh"
        isSigned: false
      - ID: 1583
        name: "hot_water_compressor_only"
        description: "Hot water compressor only"
        openMetricType: "counter"
        modbusType: 1
        length: 2
        divisor: 10
        unit: "kWh"
        isSigned: false
      - ID: 1585
        name: "heating_compressor_only"
        description: "Heating compressor only"
        openMetricType: "counter"
        modbusType: 1
        length: 2
        divisor: 10
        unit: "kWh"
        isSigned: false
      - ID: 3821
        name: "total_production"
        description: "Total production"
        openMetricType: "counter"
        modbusType: 1
        length: 2
        divisor: 10
        unit: "kWh"
        isSigned: false
      - ID: 3823
        name: "total_consumption"
        description: "Total consumption"
        openMetricType: "counter"
        modbusType: 1
        length: 2
        divisor: 10
        unit: "kWh"
        isSigned: false
      - ID: 3804
        name: "priority"
        description: "Priority"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 1
        unit: ""
        isSigned: false
      - ID: 1029
        name: "operating_mode_internal_additional_heat"
        description: "Operating mode internal additional heat"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 1
        unit: ""
        isSigned: false
      - ID: 1038
        name: "current_hot_water_mode_without_spasc"
        description: "Current hot water mode without SPA/SC"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 1
        unit: ""
        isSigned: false
      - ID: 1041
        name: "min_frequency_compressor"
        description: "Minimum frequency compressor"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 1
        unit: "Hz"
        isSigned: false
      - ID: 1042
        name: "max_frequency_compressor"
        description: "Maximum frequency compressor"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 1
        unit: "Hz"
        isSigned: false
      - ID: 1046
        name: "compressor_frequency_current"
        description: "Compressor frequency current"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 1
        unit: "Hz"
        isSigned: false
      - ID: 1065
        name: "compressor_frequency"
        description: "Compressor frequency"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 1
        unit: "Hz"
        isSigned: false
      - ID: 1047
        name: "inverter_temperature"
        description: "Inverter temperature"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 10
        unit: "°C"
        isSigned: true
      - ID: 1048
        name: "compressor_power_input"
        description: "Compressor power input"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 1
        unit: "W"
        isSigned: false
      - ID: 1052
        name: "current_compressor"
        description: "Current compressor"
        openMetricType: "gauge"
        modbusType: 1
        length: 1
        divisor: 1
        unit: "mA"
        isSigned: false
